In [7]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [10]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create an array with specified data type

In [12]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print(f'Data Type is : {arr.dtype}')

[[1 2 3]
 [4 5 6]]
Data Type is : int16


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [13]:
# np.arange(start, stop, step)
arr = np.arange(0, 21, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [21]:
arr, step_size = np.linspace(0, 5, 10, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
The step size is 0.5


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [25]:
arr = np.random.rand(3,4)
print(arr)

[[0.11826005 0.49101774 0.8226487  0.83042834]
 [0.5114849  0.92684152 0.86247823 0.01994904]
 [0.86997173 0.86566778 0.1861424  0.53202509]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [23]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [11]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int32


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [37]:
empty = np.empty((5,5))
print(empty)

[[8.28103825e-312 7.85564377e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307]
 [1.16096346e-028 1.04857803e-142 1.16467185e-028 3.25113978e-086
  2.95776535e+203]
 [1.07871611e-100 1.17367616e-076 1.13286318e-051 4.44914264e-086
  4.10123917e+223]
 [2.95776535e+203 9.97664746e+141 1.17367367e-076 3.25113977e-086
  3.28879940e-086]
 [1.07826554e-100 4.48046321e+021 4.27242939e+180 3.68777431e+180
  2.59305626e-306]]


In [38]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int64


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [16]:
full = np.full((4,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [20]:
# No axis specified, then flatten the input array first and repeat
# Data Augemnation 
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 4)) 

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]


In [40]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1)) 

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [39]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0))    

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [20]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [23]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [25]:
identity_matrix = np.eye(5)
identity_matrix.astype(int)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [24]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create an array with given values on the diagonal

In [41]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.88641057 0.90338808 0.6266739  0.02898158 0.07300508]
 [0.66710406 0.7280572  0.40568999 0.4855903  0.98478536]
 [0.8291723  0.78847404 0.15211557 0.77233461 0.44761895]
 [0.92288546 0.5203376  0.75557877 0.03540796 0.11372024]
 [0.37841373 0.79124501 0.03770323 0.29486422 0.71930133]]
Values on the diagonal: [0.88641057 0.7280572  0.15211557 0.03540796 0.71930133]


In [26]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.44008485 0.19254758 0.65707551]
 [0.06838026 0.43745833 0.22630033]
 [0.86801201 0.65430091 0.93617918]
 [0.72927673 0.61550749 0.87328398]
 [0.11083138 0.15582005 0.54587358]
 [0.80298985 0.89705779 0.18045105]
 [0.93153603 0.84343715 0.39326583]
 [0.29509183 0.49859358 0.32320668]
 [0.13389313 0.6620257  0.50146751]
 [0.69110925 0.97077549 0.11649333]]
Values on the diagonal: [0.44008485 0.43745833 0.93617918]


In [27]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
