In [2]:
import numpy as np

### set seed

In [3]:
np.random.seed(123)

### set random state which is independent from the global seed

In [3]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [4]:
# generate a random scalar
print(np.random.rand())      

0.6964691855978616


In [5]:
# generate a 1-D array
print(np.random.rand(3))           

[0.28613933 0.22685145 0.55131477]


In [6]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [7]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


### generate an array of random integers in a given interval [low, high)

In [10]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(0, 10, 5, 'i8'))

[2 4 8 0 7]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [18]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(3))
print(np.random.random(3))
print(np.random.ranf(3))
print(np.random.sample(3))

[0.11139217 0.66487245 0.88785679]
[0.69631127 0.44032788 0.43821438]
[0.7650961  0.565642   0.08490416]
[0.58267109 0.8148437  0.33706638]


### generate a random sample from a given 1-D array

In [24]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 2 1 1 1 1 1 0 1 0]


In [30]:
print(np.random.choice(7, 10))

[1 5 5 6 2 5 1 5 0 6]


In [12]:
print(np.random.choice([1,2,3], 10))

[2 2 1 3 2 3 1 2 1 3]


### shuffle an array in place

In [32]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
np.random.shuffle(arr)
print(arr)

[6 7 4 1 0 3 2 9 8 5]


### generate a permutation of an array

In [36]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [4 2 5 8 3 0 9 6 1 7]
