In [10]:
import numpy as np

In [11]:
arr = np.array(range(100)).reshape((10,10))

### select an element by row and column indices

In [12]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [13]:
print(arr);print(arr[1:3, 4:6])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[14 15]
 [24 25]]


In [14]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [6]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


### boolean indexing

In [16]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1);print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [8]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [9]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [17]:
arr = np.random.rand(10,10)

In [19]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr); print(arr[[3,1,2], [3,2,1]])       

[[0.79332773 0.89058557 0.44359054 0.46080881 0.54633142 0.35087344
  0.82985532 0.16681482 0.23332686 0.65647532]
 [0.42935878 0.65548762 0.33949297 0.1529311  0.99528381 0.43244643
  0.01508123 0.69483355 0.07829159 0.50099575]
 [0.91048437 0.56711366 0.4575777  0.80899018 0.76863989 0.73433201
  0.50785601 0.49459374 0.50520938 0.2918007 ]
 [0.98918971 0.42358596 0.99713055 0.54560825 0.95638156 0.5107962
  0.85171157 0.88756286 0.35138612 0.08889702]
 [0.90807356 0.14104813 0.06658041 0.76090358 0.34826504 0.01353094
  0.13593049 0.20469172 0.34376832 0.36729994]
 [0.76388514 0.32822858 0.90231217 0.69960315 0.78948765 0.5641615
  0.49404754 0.51638186 0.32706095 0.16314525]
 [0.07259407 0.13019807 0.40152495 0.41468915 0.29002836 0.09971018
  0.46765074 0.15451397 0.76359766 0.35280396]
 [0.89015276 0.85773685 0.08077764 0.57463592 0.32065036 0.9676531
  0.32988252 0.347147   0.32806079 0.93187591]
 [0.97472655 0.82486602 0.33392614 0.66359107 0.25070514 0.22556726
  0.45665224 0.

In [12]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.09566854 0.2190723  0.6754328 ]
 [0.28997889 0.13675444 0.07718654]
 [0.15862308 0.45510309 0.94789792]]


### dimension inference

In [13]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [14]:
arr = np.arange(16).reshape(4,4)

In [15]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [16]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [17]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
